version: '3'

services:
  app:
    container_name: app
    image: wyveo/nginx-php-fpm:latest
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - conexao

  # mysql-app:
  #   image: mysql:5.7.22
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     - MYSQL_DATABASE: laravel
  #     - MYSQL_ROOT_PASSWORD: laravel
  #   volumes:
  #     - .docker/dbdata:/var/lib/mysql

  #   networks:
  #     - conexao

networks:
  conexao:
    driver: bridge      
